version: '3'

services:
  latex:
    build:
      context: .
    volumes:
      - "./latex_sources/${FLAVOUR}:/usr/src/tex"
      - "./latex_sources/common:/usr/src/tex/common"
    command: "tectonic /usr/src/tex/${FILENAME}"
